// Code generated by mockery v2.10.4. DO NOT EDIT.

package repomock

import (
	context "context"

	dto "github.com/kesyafebriana/e-wallet-api/internal/dto"
	entity "github.com/kesyafebriana/e-wallet-api/internal/entity"

	mock "github.com/stretchr/testify/mock"

	repository "github.com/kesyafebriana/e-wallet-api/internal/repository"

	sql "database/sql"
)

// Transaction is an autogenerated mock type for the Transaction type
type Transaction struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, transaction
func (_m *Transaction) Create(ctx context.Context, transaction *dto.TransactionRequest) (*entity.Transaction, error) {
	ret := _m.Called(ctx, transaction)

	var r0 *entity.Transaction
	if rf, ok := ret.Get(0).(func(context.Context, *dto.TransactionRequest) *entity.Transaction); ok {
		r0 = rf(ctx, transaction)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.Transaction)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *dto.TransactionRequest) error); ok {
		r1 = rf(ctx, transaction)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllByWalletNumber provides a mock function with given fields: ctx, walletNumber, pagination
func (_m *Transaction) GetAllByWalletNumber(ctx context.Context, walletNumber string, pagination *dto.PaginationInfo) ([]entity.Transaction, *entity.Pagination, error) {
	ret := _m.Called(ctx, walletNumber, pagination)

	var r0 []entity.Transaction
	if rf, ok := ret.Get(0).(func(context.Context, string, *dto.PaginationInfo) []entity.Transaction); ok {
		r0 = rf(ctx, walletNumber, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]entity.Transaction)
		}
	}

	var r1 *entity.Pagination
	if rf, ok := ret.Get(1).(func(context.Context, string, *dto.PaginationInfo) *entity.Pagination); ok {
		r1 = rf(ctx, walletNumber, pagination)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*entity.Pagination)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func(context.Context, string, *dto.PaginationInfo) error); ok {
		r2 = rf(ctx, walletNumber, pagination)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// WithTrx provides a mock function with given fields: trxHandle
func (_m *Transaction) WithTrx(trxHandle *sql.Tx) repository.TransactionRepository {
	ret := _m.Called(trxHandle)

	var r0 repository.TransactionRepository
	if rf, ok := ret.Get(0).(func(*sql.Tx) repository.TransactionRepository); ok {
		r0 = rf(trxHandle)
	} else {
		r0 = ret.Get(0).(repository.TransactionRepository)
	}

	return r0
}
