package constant

const (
	OKMsg                      = "Ok"
	ExpiredTokenMsg            = "Token expired, please login again"
	ValidationErrorMsg         = "Validation error, please make sure your input is correct"
	InternalServerErrorMsg     = "Our server encounter error, please contact us again"
	DuplicateEmailMsg          = "Email already registered, please login with your existing account"
	InvalidLoginInputMsg       = "Incorrect email or password"
	UserCreatedMsg             = "Your account has been created successfully"
	UserLoggedMsg              = "You are successfully login"
	EmailNotFoundMsg           = "Email not found"
	RecipientWalletNotFoundMsg = "Recipient Wallet Number not found, pleace check your input again"
	UserNotRegisteredMsg       = "Your email not registered on our system, please check your input again"
	InvalidResetTokenMsg       = "Token invalid"
	ExpiredResetTokenMsg       = "Token expired, please request reset password token again"
	UsedTokenMsg               = "Token has been used, please request reset password token again"
	TokenSentMsg               = "Your reset password token has been sent to your email"
	PasswordChangedMsg         = "Your password has been changed successfully"
	UnauthorizedMsg            = "You're not logged yet, please log in to access this page"
	AmountTopUpMinimumMsg      = "Minimum amount for top up is Rp 50.000,00"
	AmountTopUpMaximumMsg      = "Maximum amount for top up is Rp 10.000.000,00"
	InsufficientBalanceMsg     = "Insufficient balance, please top up before do a transaction"
	TransferToAccountMsg       = "You can't transfer to your own wallet"
	TopUpSuccessMsg            = "You received a money"
	TransferSuccessMsg         = "Transfer success"
	NoGachaMsg                 = "You have no gacha attempt"
)
